//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG.Monsters.MonsterSprites {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MonsterSprites {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MonsterSprites() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG.Monsters.MonsterSprites.MonsterSprites", typeof(MonsterSprites).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                  /|
        ///  _______________)|.. 
        ///&lt;&apos;______________&lt;(,_|) 
        ///           .((()))| )) &lt;&lt; YEAAYAAAAEAAAARGH!! &gt;&gt;
        ///           (======)| \ 
        ///          ((( &quot;_&quot;()|_ \
        ///         &apos;()))(_)/_/ &apos; )
        ///         .--/_\ /(  /./
        ///        /&apos;._.--\ .-(_/  
        ///       / / )\___:___) 
        ///      ( -.&apos;.._  |  /
        ///       \  \_\ ( | )
        ///        &apos;. /\)_(_)|
        ///          &apos;-|  XX |
        ///           %%%%%%%%
        ///          / %%%%%%%\
        ///         ( /.-&apos;%%%. \ 
        ///        /(.&apos;   %%\ :|
        ///       / ,|    %  ) )
        ///     _|___)   %  (__|_
        ///     )___/       )_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BanditLeader {
            get {
                return ResourceManager.GetString("BanditLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       _,.
        ///    ,` -.)
        ///   ( _/-\\-._
        ///  /,|`--._,-^|            ,
        ///  \_| |`-._/||          ,&apos;|
        ///    |  `-, / |         /  /
        ///    |     || |        /  /
        ///     `r-._||/   __   /  /
        /// __,-&lt;_     )`-/  `./  /
        ///&apos;  \   `---&apos;   \   /  /
        ///    |           |./  /
        ///    /           //  /
        ///\_/&apos; \         |/  /
        /// |    |   _,^-&apos;/  /
        /// |    , ``  (\/  /_
        ///  \,.-&gt;._    \X-=/^
        ///  (  /   `-._//^`
        ///   `Y-.____(__}
        ///    |     {__)
        ///          ().
        /// </summary>
        internal static string BanditSecond {
            get {
                return ResourceManager.GetString("BanditSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                  ,#####,
        ///                 #_   _#
        ///                 |a` `a|
        ///                 |  u  |
        ///                 \  =  /
        ///                 |\___/|
        ///        ___ ____/:     :\____ ___
        ///      .&apos;   `.-===-\   /-===-.`   &apos;.
        ///     /      .-&quot;&quot;&quot;&quot;&quot;-.-&quot;&quot;&quot;&quot;&quot;-.      \
        ///    /&apos;             =:=             &apos;\
        ///  .&apos;  &apos; .:    o   -=:=-   o    :. &apos;  `.
        ///  (.&apos;   /&apos;. &apos;-.....-&apos;-.....-&apos; .&apos;\   &apos;.)
        ///  /&apos; ._/   &quot;.     --:--     .&quot;   \_. &apos;\
        /// |  .&apos;|      &quot;.  ---:---  .&quot;      |&apos;.  |
        /// |  : |       |  ---:---  |       | :  |
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dad {
            get {
                return ResourceManager.GetString("Dad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          ,                                      ,
        ///        |\                                      /|
        ///     ,   \&apos;._ ,                           ,  _.&apos;/   ,
        ///     |\  {&apos;. &apos;-`\,      ,-._**_.-,      ,/`-&apos; .&apos;}  /|
        ///      \`&apos;-&apos;-.  &apos;.`\      \*____*/      /`.&apos;  .-&apos;-&apos;`/
        ///    ,&apos;-&apos;-._  &apos;.  ) )     /`    `\     ( (  .&apos;  _.-&apos;-&apos;,
        ///    |\&apos;- _ &apos;.   , /     /  /&quot;&quot;\  \     \ ,  .&apos;  _ -&apos;/|
        ///     \&apos;-.   .  ; (      \_|^  ^|_/      ) ;   .  .-&apos;/
        ///      `&apos;--, . ;  {`-.      \__/      .-&apos;}  ; . ,--&apos;`
        ///      &apos;--`_. ;  { ^  \   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Harpy {
            get {
                return ResourceManager.GetString("Harpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                              ,--,  ,.-.
        ///               ,                   \,       &apos;-,-`,&apos;-.&apos; | ._
        ///              /|           \    ,   |\         }  )/  / `-,&apos;,
        ///              [ ,          |\  /|   | |        /  \|  |/`  ,`
        ///              | |       ,.`  `,` `, | |  _,...(   (      .&apos;,
        ///              \  \  __ ,-` `  ,  , `/ |,&apos;      Y     (   /_L\
        ///               \  \_\,``,   ` , ,  /  |         )         _,/
        ///                \  &apos;  `  ,_ _`_,-,&lt;._.&lt;        /         /
        ///                 &apos;,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Minotaur {
            get {
                return ResourceManager.GetString("Minotaur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                               _.--&quot;&quot;-._
        ///  .                         .&quot;         &quot;.
        /// / \    ,^.         /(     Y             |      )\
        ////   `---. |--&apos;\    (  \__..&apos;--   -   -- -&apos;&quot;&quot;-.-&apos;  )
        ///|        :|    `&gt;   &apos;.     l_..-------.._l      .&apos;
        ///|      __l;__ .&apos;      &quot;-.__.||_.-&apos;v&apos;-._||`&quot;----&quot;
        /// \  .-&apos; | |  `              l._       _.&apos;
        ///  \/    | |                   l`^^&apos;^^&apos;j
        ///        | |                _   \_____/     _
        ///        j |               l `--__)-&apos;(__.--&apos; |
        ///        | |               | /`---``-----&apos;&quot;1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Skeleton {
            get {
                return ResourceManager.GetString("Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    \\\|||///
        /// .  ======= 
        //// \| O   O |
        ///\ / \`___&apos;/ 
        /// #   _| |_
        ///(#) (     )  
        /// #\//|* *|\\ 
        /// #\/(  *  )/   
        /// #   =====  
        /// #   ( U ) 
        /// #   || ||
        ///.#---&apos;| |`----.
        ///`#----&apos; `-----&apos;.
        /// </summary>
        internal static string Woodsman {
            get {
                return ResourceManager.GetString("Woodsman", resourceCulture);
            }
        }
    }
}
