//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG.LocationSystem.LocationMaps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapSheet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapSheet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG.LocationSystem.LocationMaps.MapSheet", typeof(MapSheet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DockTown {
            get {
                return ResourceManager.GetString("DockTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dungeon {
            get {
                return ResourceManager.GetString("Dungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FaireTown {
            get {
                return ResourceManager.GetString("FaireTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IronTown {
            get {
                return ResourceManager.GetString("IronTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [ X ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KantoTown {
            get {
                return ResourceManager.GetString("KantoTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [ X ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NorthTown {
            get {
                return ResourceManager.GetString("NorthTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PalletTown {
            get {
                return ResourceManager.GetString("PalletTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlainsTown {
            get {
                return ResourceManager.GetString("PlainsTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[ X ]   |
        ///     |       |      \        |           |           |      \
        ///     |   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SomeTown {
            get {
                return ResourceManager.GetString("SomeTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                       Region Name
        ///
        ///        ________
        ///       /        \                  
        ///      /  [   ]   \                        ___
        ///     |   KANTO    |                   ___/   \__     __
        ///     |      \     |                 _/          \___/  \_
        ///     |       \    |              __/    [  ]-       SOME \_
        ///     |       |    |            _/      NORTH \      TOWN   \
        ///     |       |     \          /        TOWN   \-----[  ]   |
        ///     |       |      \        |           |           |      \
        ///     |    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Woods {
            get {
                return ResourceManager.GetString("Woods", resourceCulture);
            }
        }
    }
}
