//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG.LocationSystem.LocationSprites {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocationSprites {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationSprites() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPG.LocationSystem.LocationSprites.LocationSprites", typeof(LocationSprites).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to               /\
        ///             /\/\
        ///            _|/\|_
        ///           |______|
        ///            |\/\/|
        ///           \|/\/\|   .&apos;&apos;`/:
        ///   :\&apos;&apos;.    \`&apos;. |  ||  /  :
        ///   : \ ||   |\ |||  || /    o
        ///   j _\||__/__\||_\_||/___
        ///     |___________________|
        ///      |  |   |   |   |  |
        ///~~~~~~|~~|~~~|~~~|~~~|~~|~~~~~~.
        /// </summary>
        internal static string DockTown {
            get {
                return ResourceManager.GetString("DockTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  _____________________________________________
        ///|.&apos;&apos;,                Dungeon              ,&apos;&apos;.|
        ///|.&apos;.&apos;&apos;,                                 ,&apos;&apos;.&apos;.|
        ///|.&apos;.&apos;.&apos;&apos;,                             ,&apos;&apos;.&apos;.&apos;.|
        ///|.&apos;.&apos;.&apos;.&apos;&apos;,                         ,&apos;&apos;.&apos;.&apos;.&apos;.|
        ///|.&apos;.&apos;.&apos;.&apos;.|                         |.&apos;.&apos;.&apos;.&apos;.|
        ///|.&apos;.&apos;.&apos;.&apos;.|===;                 ;===|.&apos;.&apos;.&apos;.&apos;.|
        ///|.&apos;.&apos;.&apos;.&apos;.|:::|&apos;,             ,&apos;|:::|.&apos;.&apos;.&apos;.&apos;.|
        ///|.&apos;.&apos;.&apos;.&apos;.|---|&apos;.|, _______ ,|.&apos;|---|.&apos;.&apos;.&apos;.&apos;.|
        ///|.&apos;.&apos;.&apos;.&apos;.|:::|&apos;.|&apos;|???????|&apos;|.&apos;|:::|.&apos;.&apos;.&apos;.&apos;.|
        ///|,&apos;,&apos;,&apos;,&apos;,|---|&apos;,|&apos;|??? [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dungeon {
            get {
                return ResourceManager.GetString("Dungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                   |&gt;&gt;&gt;
        ///                                  |
        ///                    |&gt;&gt;&gt;      _  _|_  _         |&gt;&gt;&gt;
        ///                    |        |;| |;| |;|        |
        ///                _  _|_  _    \\.    .  /    _  _|_  _
        ///               |;|_|;|_|;|    \\:. ,  /    |;|_|;|_|;|
        ///               \\..      /    ||;   . |    \\.    .  /
        ///                \\.  ,  /     ||:  .  |     \\:  .  /
        ///                 ||:   |_   _ ||_ . _ | _   _||:   |
        ///                 ||:  .|||_|;|_|;|_|;|_|;|_|;||:.  |
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                  .&apos;&apos;.
        ///       .&apos;&apos;.             *&apos;&apos;*    :_\/_:     . 
        ///      :_\/_:   .    .:.*_\/_*   : /\ :  .&apos;.:.&apos;.
        ///  .&apos;&apos;.: /\ : _\(/_  &apos;:&apos;* /\ *  : &apos;..&apos;.  -=:o:=-
        /// :_\/_:&apos;.:::. /)\*&apos;&apos;*  .|.* &apos;.\&apos;/.&apos;_\(/_&apos;.&apos;:&apos;.&apos;
        /// : /\ : :::::  &apos;*_\/_* | |  -= o =- /)\    &apos;  *
        ///  &apos;..&apos;  &apos;:::&apos;   * /\ * |&apos;|  .&apos;/.\&apos;.  &apos;._____
        ///      *        __*..* |  |     :      |.   |&apos; .---&quot;|
        ///       _*   .-&apos;   &apos;-. |  |     .--&apos;|  ||   | _|    |
        ///    .-&apos;|  _.|  |    ||   &apos;-__  |   |  |    ||      |
        ///    |&apos; | |.    |    || [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FaireTown {
            get {
                return ResourceManager.GetString("FaireTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                    /\
        ///                              /\  //\\
        ///                       /\    //\\///\\\        /\
        ///                      //\\  ///\////\\\\  /\  //\\
        ///         /\          /  ^ \/^ ^/^  ^  ^ \/^ \/  ^ \
        ///        / ^\    /\  / ^   /  ^/ ^ ^ ^   ^\ ^/  ^^  \
        ///       /^   \  / ^\/ ^ ^   ^ / ^  ^    ^  \/ ^   ^  \       *
        ///      /  ^ ^ \/^  ^\ ^ ^ ^   ^  ^   ^   ____  ^   ^  \     /|\
        ///     / ^ ^  ^ \ ^  _\___________________|  |_____^ ^  \   /||o\
        ///    / ^^  ^ ^ ^\  /____________ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IronTown {
            get {
                return ResourceManager.GetString("IronTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                   \  |  /         ___________
        ///   ____________  \ \_# /         |  ___      |       _________
        ///  |            |  \  #/          | |   |     |      | = = = = |
        ///  | |   |   |  |   \\#           | |`v&apos;|     |      |         |
        ///  |            |    \#  //       |  --- ___  |      | |  || | |
        ///  | |   |   |  |     #_//        |     |   | |      |         |
        ///  |            |  \\ #_/_______  |     |   | |      | |  || | |
        ///  | |   |   |  |   \\# /_____/ \ |      ---  |      |         |
        ///  |         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KantoTown {
            get {
                return ResourceManager.GetString("KantoTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                        X_x
        ///                      / \\\
        ///                      |n| |
        ///                    )(|_|-&apos;X
        ///                   /  \\Y// \
        ///                   |A | | |A|
        ///                   |  | | |_|
        ///            )(__X,,|__|MEB;;;-,)(,
        ///           /  \\\;;;;;;;;;;;;/    \
        ///           |A | |            | U  |
        ///         )_|  | |____)-----( |    |
        ///        ///|__|-&apos;////       \|___)=(__X
        ///       /////////////         \///   \/ \
        ///       |           |  U    U |//     \u|
        ///       |   )_,-,___|_)=(     |  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NorthTown {
            get {
                return ResourceManager.GetString("NorthTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to              )                              (
        ///            (                                 )
        ///    ________[]_                              []
        ///   /^=^-^-^=^-^\                   /^~^~^~^~^~^~\
        ///  /^-^-^-^-^-^-^\                 /^ ^ ^  ^ ^ ^ ^\
        /// /__^_^_^_^^_^_^_\               /_^_^_^^_^_^_^_^_\
        ///  |  .==.       |                 |        .--.  |
        ///^^|  |LI|  [}{] |^^^^^^^^^^^^^^^^^|  [}{]  |[]|  |^^^^^
        ///&amp;&amp;|__|__|_______|&amp;&amp;             88|________|__|__|888
        ///     ====                                  ==== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PalletTown {
            get {
                return ResourceManager.GetString("PalletTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                            |&gt;&gt;&gt;
        ///                   _                      _                |
        ///    ____________ .&apos; &apos;.    _____/----/-\ .&apos; &apos;./========\   / \
        ///   //// ////// /V_.-._\  |.-.-.|===| _ |-----| u    u |  /___\
        ///  // /// // ///==\ u |.  || | ||===||||| |T| |   ||   | .| u |_ _ _ _ _ _
        /// ///////-\////====\==|:::::::::::::::::::::::::::::::::::|u u| U U U U U
        /// |----/\u |--|++++|..|&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;::::::::::::::&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;&apos;|+++|+-+-+-+-+-+
        /// |u u|u | |u ||||||..|             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlainsTown {
            get {
                return ResourceManager.GetString("PlainsTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~         ~~          __
        ///       _T      .,,.    ~--~ ^^
        /// ^^   // \                    ~
        ///      ][O]    ^^      ,-~ ~
        ///   /&apos;&apos;-I_I         _II____
        ///__/_  /   \ ______/ &apos;&apos;   /&apos;\_,__
        ///  | II--&apos;&apos;&apos;&apos; \,--:--..,_/,.-{ },
        ///; &apos;/__\,.--&apos;;|   |[] .-.| O{ _ }
        ///:&apos; |  | []  -|   &apos;&apos;--:.;[,.&apos;\,/
        ///&apos;  |[]|,.--&apos;&apos; &apos;&apos;,   &apos;&apos;-,.    |
        ///  ..    ..-&apos;&apos;    ;       &apos;&apos;. &apos;.
        /// </summary>
        internal static string SomeTown {
            get {
                return ResourceManager.GetString("SomeTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ///⠀⠀⠀⢀⣼⣦⠀⠀⣠⣿⣿⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⣆⠀⠀⠀⠀⠀
        ///⠀⠀⠒⣿⣿⣿⠓⠀⠀⠻⣿⣿⠀⢀⣴⣿⣦⡀⠀⢀⣾⣦⠘⢿⣿⣧⡀⠀⠀⠀
        ///⠀⢀⣴⣿⡿⠃⡄⠈⠻⣿⣟⣉⣀⠉⣽⡿⠋⠡⠴⣿⣿⣿⠓⠀⠙⢇⠀⠀⠀⠀
        ///⠀⠿⣿⠟⢁⣾⣿⣦⣀⠘⠿⠟⢁⣼⣿⣿⣷⠂⣴⣿⣿⣿⣆⠘⢶⣶⣿⠶⠤⠀
        ///⠀⣀⣀⡀⢉⣿⣿⣿⡍⠀⢀⣀⠙⢻⠿⢋⣤⣾⣿⣿⣿⣿⣿⣷⣄⠙⢿⣦⡀⠀
        ///⠀⠟⠋⣠⣾⣿⣿⣿⣿⣦⣌⠉⠠⣤⣤⣤⡌⢙⣿⣿⣿⣿⣿⣿⠛⠛⠂⢈⣙⠀
        ///⠀⠀⣉⡉⣹⣿⣿⣿⣿⣏⠉⣉⣀⣈⠙⠋⣠⣿⣿⣿⣿⣿⣿⣿⣆⠙⠛⠛⠛⠀
        ///⠀⠀⠋⣴⣿⣿⣿⣿⣿⣿⣷⣌⠉⢁⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀
        ///⠀⠴⢾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠦⠈⣙⠛⠛⠛⠛⠛⠛⠛⠛⣉⣉⠁⠀⠀⠀
        ///⠀⠀⣦⣤⡄⢉⣉⣉⣉⠉⣡⣤⠀⠀⠀⣿⣿⣷⠀⢰⣿⣿⡇⢸⣿⣿⠀⠀⠀⠀
        ///⠀⠀⣿⣿⡇⣸⣿⣿⣿⡄⢻⣿⠀⠀⠀⣿⣿⣿⠀⢸⣿⣿⡇⢸⣿⣿⠀⠀⠀⠀
        ///⠀⠀⣿⣿⠁⣿⣿⣿⣿⡇⠸⠿⠀⠀⠀⣿⣿⣿⠀⢸⣿⣿⣇⠸⣿⣿⠀⠀⠀⠀
        ///⠀⠀⠛⠛⠀⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠉⠉⠉⠀⢸⣿⣿⣿⠀⠿⠿⠀⠀⠀⠀
        ///⠀⠀⠀⠀⠀⠛⠛⠛⠛⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠀⠀⠀⠀⠀⠀⠀.
        /// </summary>
        internal static string Woods {
            get {
                return ResourceManager.GetString("Woods", resourceCulture);
            }
        }
    }
}
